import { ColorModeScript, Flex } from "@chakra-ui/react";
import type { Metadata } from "next";
import { usePathname } from "next/navigation";

import { Header } from "@/components/header/header";

import { fonts } from "./fonts";
import { Providers } from "./providers";
import { theme } from "./theme";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={fonts.oswald.className}>
      <body>
        <Providers>
          <ColorModeScript initialColorMode={theme.config.initialColorMode} />
          <Header>{children}</Header>
        </Providers>
      </body>
    </html>
  );
}
